services:
  api-auth:
    container_name: chess_api_auth
    build:
      context: ./nest
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./env/cors.env
    environment:
      PORT: 3000
      RABBIT_MQ_URI: amqp://rabbitmq:5672
      JWT_EXPIRATION: 604800 # 7 days
      JWT_SECRET: secret123
    depends_on:
      - mongo-primary
    volumes:
      - ./nest:/app
      - /app/node_modules
    ports:
      - 3001:3000

  api-games:
    container_name: chess_api_games
    build:
      context: ./nest
      dockerfile: ./apps/games/Dockerfile
      target: development
    command: yarn start:dev games
    env_file:
      - ./env/mongo.env
      - ./env/cors.env
    environment:
      PORT: 3000
      RABBIT_MQ_URI: amqp://rabbitmq:5672
      REDIS_HOST: redis
    depends_on:
      - mongo-primary
    volumes:
      - ./nest:/app
      - /app/node_modules
    ports:
      - 3002:3000

  api-players:
    container_name: chess_api_players
    build:
      context: ./nest
      dockerfile: ./apps/players/Dockerfile
      target: development
    command: yarn start:dev players
    env_file:
      - ./env/mongo.env
      - ./env/cors.env
    environment:
      PORT: 3000
      RABBIT_MQ_URI: amqp://rabbitmq:5672
    depends_on:
      - mongo-primary
    volumes:
      - ./nest:/app
      - /app/node_modules
    ports:
      - 3003:3000

  rabbitmq:
    container_name: chess_rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  
  reverse-proxy:
    container_name: chess_reverse_proxy
    image: nginx:1.19.6
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-auth
      - api-games
      - api-players

  mongo-primary:
    container_name: chess_mongo_primary
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - 'mongodb_master_data:/data/db'

  mongo-express:
    container_name: chess_mongo_express
    image: mongo-express
    depends_on:
      - mongo-primary
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://root:password123@mongo-primary:27017/

volumes:
  mongodb_master_data:
