services:
  api-auth:
    container_name: chess_prod_api_auth
    build:
      context: ./nest
      dockerfile: ./apps/auth/Dockerfile
      target: production
    environment:
      PORT: 3000
      RABBIT_MQ_URI: ${RABBIT_MQ_URI}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_SECRET: ${JWT_SECRET}
      ORIGIN: ${ORIGIN}
    depends_on:
      - mongo-primary
      - rabbitmq
    ports:
      - 3001:3000

  api-games:
    container_name: chess_prod_api_games
    build:
      context: ./nest
      dockerfile: ./apps/games/Dockerfile
      target: production
    environment:
      PORT: 3000
      RABBIT_MQ_URI: ${RABBIT_MQ_URI}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      ORIGIN: ${ORIGIN}
    depends_on:
      - mongo-primary
      - rabbitmq
    ports:
      - 3002:3000

  api-players:
    container_name: chess_prod_api_players
    build:
      context: ./nest
      dockerfile: ./apps/players/Dockerfile
      target: production
    environment:
      PORT: 3000
      RABBIT_MQ_URI: ${RABBIT_MQ_URI}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      ORIGIN: ${ORIGIN}
    depends_on:
      - mongo-primary
      - rabbitmq
    ports:
      - 3003:3000

  rabbitmq:
    container_name: chess_prod_rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672

  reverse-proxy:
    container_name: chess_prod_reverse_proxy
    image: nginx:1.19.6
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.production.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-auth
      - api-games
      - api-players

  mongo-primary:
    container_name: chess_prod_mongo_primary
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - 'mongodb_prod_data:/data/db'

volumes:
  mongodb_prod_data:
